---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 826b1bfcf77ccb37791c0dfd3a052d1f0d5169d6
    app.quarkus.io/build-timestamp: 2023-02-28 - 09:15:18 +0000
  labels:
    app.kubernetes.io/name: bootcampapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: bootcampapp
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: bootcampapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 826b1bfcf77ccb37791c0dfd3a052d1f0d5169d6
    app.quarkus.io/build-timestamp: 2023-02-28 - 09:15:18 +0000
  labels:
    app.kubernetes.io/name: bootcampapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: bootcampapp
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: bootcampapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: s2i-java
spec:
  dockerImageRepository: fabric8/s2i-java
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 826b1bfcf77ccb37791c0dfd3a052d1f0d5169d6
    app.quarkus.io/build-timestamp: 2023-02-28 - 09:15:18 +0000
  labels:
    app.kubernetes.io/name: bootcampapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: bootcampapp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: bootcampapp:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-java:2.3
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 826b1bfcf77ccb37791c0dfd3a052d1f0d5169d6
    app.quarkus.io/build-timestamp: 2023-02-28 - 09:15:18 +0000
  labels:
    app.kubernetes.io/name: bootcampapp
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: bootcampapp
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: bootcampapp
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 826b1bfcf77ccb37791c0dfd3a052d1f0d5169d6
        app.quarkus.io/build-timestamp: 2023-02-28 - 09:15:18 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: bootcampapp
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
            - name: CACHENAME
              value: testgrid1
            - name: CACHESERVICE
              value: kneuralgrid
          image: uther/bootcampapp:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: bootcampapp
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - bootcampapp
        from:
          kind: ImageStreamTag
          name: bootcampapp:1.0.0-SNAPSHOT
      type: ImageChange
